admin_category:
    pattern:  /
    defaults: { _controller: LiderBundle:Category:checkRoute }

admin_category_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Category:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_category_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Category:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_category_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Category:list }
    methods:  [GET]
    requirements:
      id: \d+