admin_duel:
    pattern:  /
    defaults: { _controller: LiderBundle:Duel:checkRoute }
    methods: [GET]

admin_duels_getbygameid:
    pattern:  /game/{gameId}
    defaults: { _controller: LiderBundle:Duel:getDuelsByGame }
    methods:  [GET]
    requirements:
      id: \d+

get_duels_getquestionsbyduel:
    pattern:  /questions/{duelId}
    defaults: { _controller: LiderBundle:Duel:getQuestionsFromDuel }
    methods: [GET]

get_duels_notificationduel:
    pattern:  /notification/{duelId}
    defaults: { _controller: LiderBundle:Duel:notificationByDuel }
    methods: [GET]

close_duel_manual:
    pattern:  /close
    defaults: { _controller: LiderBundle:Duel:closeDuelManual }
    methods: [GET]