duels_game_params:
    pattern:  /duels/{gameId}
    defaults: { _controller: LiderBundle:Game:getGameDuels}
    methods: [GET]

admin_game:
    pattern:  /
    defaults: { _controller: LiderBundle:Game:checkRoute }

admin_game_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Game:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_game_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Game:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_game_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Game:list }
    methods:  [GET]
    requirements:
      id: \d+

admin_game_getbygroup:
    pattern:  /group/{tournament}
    defaults: { _controller: LiderBundle:Game:getGamesByGroup }
    methods:  [GET]
    requirements:
      id: \d+

stop_game:
    pattern:  /stop
    defaults: { _controller: LiderBundle:Game:stopGames }
    methods:  [GET]

start_game:
    pattern:  /start
    defaults: { _controller: LiderBundle:Game:startGames }
    methods:  [GET]

stop_game_manual:
    pattern:  /stop/{gameId}
    defaults: { _controller: LiderBundle:Game:stopGameManual }
    methods:  [GET]

send_game_notification:
    pattern:  /notification/{gameId}
    defaults: { _controller: LiderBundle:Game:sendNotificationByGame }
    methods:  [GET]

prueba_game_2:
    pattern:  /prueba/{gameId}
    defaults: { _controller: LiderBundle:Game:getPointsGame }
    methods:  [GET]