admin_group:
    pattern:  /
    defaults: { _controller: LiderBundle:Group:checkRoute }

admin_group_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Group:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_group_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Group:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_group_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Group:list }
    methods:  [GET]
    requirements:
      id: \d+

admin_group_geneate:
    pattern:  /generate
    defaults: { _controller: LiderBundle:Group:generateGroup }
    methods:  [GET]

admin_group_save:
    pattern:  /save
    defaults: { _controller: LiderBundle:Group:saveGroup }
    methods:  [POST]

admin_group_notification:
    pattern:  /notification/{tournamentId}    
    defaults: { _controller: LiderBundle:Group:notificationGroup }
    methods:  [GET]