admin_office:
    pattern:  /
    defaults: { _controller: LiderBundle:Office:checkRoute }
    
admin_office_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Office:delete }
    methods:  [DELETE]
    requirements:
      id: \d+
      
admin_office_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Office:update }
    methods:  [PUT]
    requirements:
      id: \d+
      
admin_office_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Office:list }
    methods:  [GET]
    requirements:
      id: \d+