admin_parameters:
    pattern:  /
    defaults: { _controller: LiderBundle:Parameters:checkRoute }

admin_parameters_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Parameters:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_parameters_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Parameters:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_parameters_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Parameters:list }
    methods:  [GET]
    requirements:
      id: \d+
