admin_player:
    pattern:  /
    defaults: { _controller: LiderBundle:Player:checkRoute }

admin_player_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Player:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_player_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Player:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_player_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Player:list }
    methods:  [GET]
    requirements:
      id: \d+