admin_question:
    pattern:  /
    defaults: { _controller: LiderBundle:Question:checkRoute }
    
admin_question_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:delete }
    methods:  [DELETE]
    requirements:
      id: \d+
      
admin_question_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:update }
    methods:  [PUT]
    requirements:
      id: \d+
      
admin_question_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:list }
    methods:  [GET]
    requirements:
      id: \d+