admin_question:
    pattern:  /
    defaults: { _controller: LiderBundle:Question:checkRoute }

admin_question_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_question_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_question_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Question:list }
    methods:  [GET]
    requirements:
      id: \d+

admin_question_checkbyid:
    pattern:  /check/{id}
    defaults: { _controller: LiderBundle:Question:check }
    methods:  [POST]
    requirements:
      id: \d+      

admin_question_image:
    pattern:  /image/{id}
    defaults: { _controller: LiderBundle:Question:setImage }
    methods:  [POST]
    requirements:
      id: \d+   

admin_question_remove_image:
    pattern:  /image/{id}/remove
    defaults: { _controller: LiderBundle:Question:removeImage }
    methods:  [POST]

admin_question_report:
    pattern:  /report
    defaults: { _controller: LiderBundle:ReportQuestion:getReportQuestions }
    methods:  [GET]
    requirements:
      id: \d+

admin_question_report_solve:
    pattern:  /report/solve/{id}
    defaults: { _controller: LiderBundle:ReportQuestion:reportSolve }
    methods:  [PUT]