admin_team:
    pattern:  /
    defaults: { _controller: LiderBundle:Team:checkRoute }

admin_team_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

admin_team_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:update }
    methods:  [PUT]
    requirements:
      id: \d+

admin_team_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:list }
    methods:  [GET]
    requirements:
      id: \d+

admin_team_image:
    pattern:  /image/{id}
    defaults: { _controller: LiderBundle:Team:setImage }
    methods:  [POST]
    requirements:
      id: \d+

admin_team_geneate:
    pattern:  /generate
    defaults: { _controller: LiderBundle:Team:generateTeam }
    methods:  [GET]

admin_team_save:
    pattern:  /save
    defaults: { _controller: LiderBundle:Team:saveTeam }
    methods:  [POST]

admin_update_team_tournament:
    pattern:  /tournament
    defaults: { _controller: LiderBundle:Team:updateTeamTournament }
    methods:  [GET]

admin_team_notification:
    pattern:  /notification
    defaults: { _controller: LiderBundle:Team:notificationTeam }
    methods:  [GET]