imports:
    - { resource: config.yml }


services:
    kernel.listener.exceptionlistener:
        class: Lider\Bundle\LiderBundle\Lib\ExceptionListener
        arguments:
              request: "@talker"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
