imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

#parameters:

#services:                

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          LiderBundle: ~

# MongoDB configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://10.102.1.21:27017
            #server: mongodb://localhost:27017
            options: {}
    default_database: lider
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#hwi_oauth:
#    firewall_name: admin_area 
#    resource_owners:
#        google:
#            type:                google
#            client_id:           409288717107-h73ade2t3homia8e8r6o4dg3bmuingn3.apps.googleusercontent.com  
#            client_secret:       E4OBnryE-9dRSlMOYAvxXePm
#            scope:               "email profile"

nelmio_cors:
    defaults:
         allow_origin: []
         allow_headers: []
         allow_methods: []
         max_age: 3600
    paths:
        '^/login':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']
            max_age: 3600
        '^/home/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            
        # '^/':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['OPTIONS']
        #     max_age: 3600

        # '^/home/player/profile':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600
        # '^/home/question/answer/check':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600
        # '^/home/question/report':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600       

