imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

#parameters:

services:
    lider_listener:
        class: Lider\Bundle\LiderBundle\EventListener\SerialListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments:
              container: "@service_container"

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        gc_probability: 0
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
          LiderBundle: ~

# MongoDB configuration
doctrine_mongodb:
    connections:
        default:
            # server: mongodb://10.102.1.21:27017
            # server: mongodb://10.101.1.135:27017
            server: mongodb://%mongo_host%:%mongo_port%
            # server: mongodb://%mongo_user%:%mongo_pass%@%mongo_host%:%mongo_port%

            options: {}
    default_database: lider
    document_managers:
        default:
            auto_mapping: true

doctrine_cache:
    providers:
        gearman_cache:
            type: file_system
            namespace: doctrine_cache.ns.gearman

gearman:
   # Bundles will parsed searching workers
   bundles:
      # Name of bundle
      LiderBundle:

         # Bundle name
         name: LiderBundle

         # Bundle search can be enabled or disabled
         active: true

         # If any include is defined, Only these namespaces will be parsed
         # Otherwise, full Bundle will be parsed
         include:
            - Worker

         # Namespaces this Bundle will ignore when parsing
         ignore:
            - DependencyInjection
            - Resources

   # default values
   # All these values will be used if are not overwritten in Workers or jobs
   defaults:

      # Default method related with all jobs
      # do // deprecated as of pecl/gearman 1.0.0. Use doNormal
      # doNormal
      # doBackground
      # doHigh
      # doHighBackground
      # doLow
      # doLowBackground
      method: doNormal

      # Default number of executions before job dies.
      # If annotations defined, will be overwritten
      # If empty, 0 is defined by default
      iterations: 0

      # execute callbacks after operations using Kernel events
      callbacks: true

      # Prefix in all jobs
      # If empty name will not be modified
      # Useful for rename jobs in different environments
      job_prefix: null

      # Autogenerate unique key in jobs/tasks if not set
      # This key is unique given a Job name and a payload serialized
      generate_unique_key: true

      # Prepend namespace when callableName is built
      # By default this variable is set as true
      workers_name_prepend_namespace: true

   # Server list where workers and clients will connect to
   # Each server must contain host and port
   # If annotations defined, will be full overwritten
   #
   # If servers empty, simple localhost server is defined by default
   # If port empty, 4730 is defined by efault
   servers:
      localhost:
         host: %gearman_host%
         port: %gearman_port%

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#hwi_oauth:
#    firewall_name: admin_area 
#    resource_owners:
#        google:
#            type:                google
#            client_id:           409288717107-h73ade2t3homia8e8r6o4dg3bmuingn3.apps.googleusercontent.com  
#            client_secret:       E4OBnryE-9dRSlMOYAvxXePm
#            scope:               "email profile"

nelmio_cors:
    defaults:
         allow_origin: []
         allow_headers: []
         allow_methods: []
         max_age: 3600
    paths:
        '^/login':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET']
            max_age: 3600
        '^/home/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600

        # '^/':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['OPTIONS']
        #     max_age: 3600

        # '^/home/player/profile':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600
        # '^/home/question/answer/check':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600
        # '^/home/question/report':
        #     allow_origin: ['*']
        #     allow_headers: ['*']
        #     allow_methods: ['POST', 'OPTIONS']
        #     max_age: 3600       

avalanche_imagine:
    filters:
        my_thumb:
            type:    thumbnail
            options: { size: [120, 90], mode: outbound, cache_type: public, cache_expires: 2 weeks }
