hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /admin/login
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /admin/connect
    
google_login_check:
    pattern: /admin/login-check/google

admin_login_check:
    pattern: /admin/login-check
    
admin_logout:
    path:   /admin/logout

liderBundle:
    resource: "@LiderBundle/Resources/config/routing.yml"
    prefix:   /