security:
    encoders:
        Lider\Bundle\LiderBundle\Entity\Player:
             algorithm: sha1
             encode_as_base64: false
             iterations: 250

#   role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        userprovider:
            id: my_user_provider

    firewalls:
        admin_area:
            pattern:   ^/admin
            anonymous: ~
            oauth:
                resource_owners:
                    google: /login/check-google
                    
                login_path: /admin/
                check_path: /admin/login_check
                default_target_path: admin_home_page
                use_forward: true                
                always_use_default_target_path: true
                                
                failure_path: /admin/
                
                failure_forward: true
                
                oauth_user_provider:
                    service: my_user_provider
                
            logout:
                 path:   admin_logout
                 target: admin_index_page

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }