security:
    acl:
       connection: default
        
    encoders:
        Lider\Bundle\LiderBundle\Entity\Player:
             algorithm: sha1
             encode_as_base64: false
             iterations: 250

#   role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Lider\Bundle\LiderBundle\Entity\Player, property: email }
            
        userprovider:
            id: my_user_provider

    firewalls:
        admin_area:
            pattern:   ^/admin
            anonymous: ~
            form_login:
                check_path: admin_login_check
                login_path: admin_index_page
                
                failure_forward: true                         
                failure_path: admin_check_failure
                
                default_target_path: admin_home_page
                use_forward: true
                
            oauth:                                        
                login_path: admin_index_page
                check_path: admin_login_check
                
                failure_forward: true                         
                failure_path: admin_check_failure
                
                default_target_path: admin_home_page
                use_forward: true
                
                use_referer: false
                
                resource_owners:
                    google: /admin/login-check/google
                                    
                oauth_user_provider:
                    service: my_user_provider

            logout:
                 path:   admin_logout
                 target: admin_index_page

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }