security:
    encoders:
        Lider\Bundle\LiderBundle\Entity\Player:
             algorithm: sha1
             encode_as_base64: false
             iterations: 250

#   role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Lider\Bundle\LiderBundle\Entity\Player, property: email }

    firewalls:
        admin_area:
            pattern:   ^/admin
            anonymous: ~
            form_login:
                login_path: admin_index_page
                check_path: admin_login_check
                
                default_target_path: admin_home_page
                use_forward: true
                
                always_use_default_target_path: true
                
                failure_path: admin_index_page
                failure_forward: true
                
            logout:
                 path:   admin_logout
                 target: admin_index_page

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }