security:
       
    encoders:
        Lider\Bundle\LiderBundle\Entity\Player:
             algorithm: sha1
             encode_as_base64: false
             iterations: 250

#   role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Lider\Bundle\LiderBundle\Entity\Player, property: email }
        userprovider:
            id: lider_user_provider

    firewalls:
        admin_area:
            pattern:   ^/admin
            anonymous: ~
            provider: main
            elogin: 
                login_path: admin_index_page
                check_path: /admin/check/google
                failure_path: admin_index_page
                default_target_path: /admin/home
 #           provider: userprovider
 #           oauth:
 #               resource_owners:
 #                   google:             "/admin/check/google"
 #               check_path:   /admin/login-check
 #               login_path:   /admin

 #               failure_path: /admin
 #               oauth_user_provider:
 #                   service: lider_user_provider
            form_login:
                login_path: admin_index_page
                check_path: /admin/check
                default_target_path: admin_home_page            
                use_forward: true
#				        username_parameter:             _username
#               password_parameter:             _password

                #Redirigir en ingreso satisfactorio
                #always_use_default_target_path: false


                #opciones para redirigir en ingreso fallido 
                failure_path: admin_index_page
                failure_forward: true

            logout:
                 path:   admin_logout
                 target: admin_index_page

        player_area:
            pattern:   ^/
#            host: soylider.sifinca.net
            http_basic: true
            anonymous: ~
            provider: userprovider
            hauth: true
#            elogin: 
#                login_path: player_index_page
#                check_path: /player/login-check/google
#                failure_path: player_index_page
#                default_target_path: /player/home
            form_login: ~

    access_control:
        - { path: ^/admin/home, roles: [ROLE_ADMIN] }
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/send, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/home, roles: IS_AUTHENTICATED_ANONYMOUSLY }
