question_test:
    pattern:  /test
    defaults: { _controller: LiderBundle:Question:getTestQuestion }
    methods:  [GET]
    
answer_check:
    pattern:  /answer/check
    defaults: { _controller: LiderBundle:Question:checkAnswer }
    methods:  [POST]      