player_team:
    pattern:  /
    defaults: { _controller: LiderBundle:Team:checkRoute }

player_team_delete:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:delete }
    methods:  [DELETE]
    requirements:
      id: \d+

player_team_update:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:update }
    methods:  [PUT]
    requirements:
      id: \d+

player_team_getbyid:
    pattern:  /{id}
    defaults: { _controller: LiderBundle:Team:list }
    methods:  [GET]
    requirements:
      id: \d+