gamesParameters:
    timeQuestionPractice: '30'
    timeQuestionDuel: '30'
    timeGame: '6'
    timeDuel: '2'
    answerShowPractice: 'false'
    answerShowGame: 'false'
    timeDuelExtra: '1'
    countQuestionDuel: '5'
    countQuestionDuelExtra: '1'
    gamePoints: '1'
    gamePointsHelp: '3'
    questionPoints: '3'
    questionPointsHelp: '1'
    countQuesttionExtraDuel: '1'
    pointExtraDuel: 'false'
