lider_homepage:
    path:     /hello/{name}
    defaults: { _controller: LiderBundle:Default:index }

lider_index_page:
    path:     /
    defaults: { _controller: LiderBundle:Routing:loginPage }

login_check:
    path: /login_check

lider:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin

lider_home_administrator_page:
    path:     /home
    defaults: { _controller: LiderBundle:Routing:homeAdministratorPage }


