lider:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin
    
default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }