default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }

admin_module:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin
    host: soylider.sifinca.net

player_module:
    resource: "@LiderBundle/Resources/config/player_routes/routing.yml"
    prefix:   /
    host: soylider.sifinca.net   

image_route:
    pattern:  /image/{id}
    defaults: { _controller: LiderBundle:Image:get }
    methods:  [GET]

send:
    pattern:  /send
    defaults: { _controller: LiderBundle:Default:sendEmail }

mongo:
    pattern:  /mongo
    defaults: { _controller: LiderBundle:Default:mongoData }

general_image:
    pattern:  /image
    defaults: { _controller: LiderBundle:Image:saveImage }
    methods:  [POST]

<<<<<<< HEAD
#admin_question_prueba:
#    pattern:  /parameters/prueba
#    defaults: { _controller: LiderBundle:Question:prueba }
#    # methods:  [POST]
=======
>>>>>>> 04274697c04bff3cf2d81cd0bac2621866642fd1
