lider_homepage:
    path:     /hello/{name}
    defaults: { _controller: LiderBundle:Default:index }

lider_index_page:
    path:     /
    defaults: { _controller: LiderBundle:Routing:loginPage }

lider:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin

default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }

admin_home:
    path: /admin/home
    defaults: { _controller: LiderBundle:Routing:homeAdministratorPage }
