default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }

admin_module:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin
    #host: soylider.sifinca.net

player_module:
    resource: "@LiderBundle/Resources/config/player_routes/routing.yml"
    prefix:   /
    #host: soylider.sifinca.net   

image_route:
    pattern:  /image/{id}
    defaults: { _controller: LiderBundle:Image:get }
    methods:  [GET]
admin_question_prueba:
    pattern:  /parameters/prueba
    defaults: { _controller: LiderBundle:Question:prueba }
    # methods:  [POST]
