default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }

admin_module:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin

player_module:
    resource: "@LiderBundle/Resources/config/player_routes/routing.yml"
    prefix:   /player
