default_data:
    pattern:  /default
    defaults: { _controller: LiderBundle:Default:createDefaultData }

admin_module:
    resource: "@LiderBundle/Resources/config/admin_routes/routing.yml"
    prefix:   /admin
    # host: soylider.sifinca.net
    #host: lider.sifinca.net

player_module:
    resource: "@LiderBundle/Resources/config/player_routes/routing.yml"
    prefix:   /
    #host: lider.sifinca.net

image_route:
    pattern:  /image/{id}
    defaults: { _controller: LiderBundle:Image:get }
    methods:  [GET]

send:
    pattern:  /send
    defaults: { _controller: LiderBundle:Default:sendEmail }

mongo:
    pattern:  /mongo
    defaults: { _controller: LiderBundle:Default:mongoData }