parameters:
#    lider.example.class: Lider\Bundle\LiderBundle\Example

services:
#    lider.example:
#        class: %lider.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
