parameters:
    lider.security.core.provider.class: Lider\Bundle\LiderBundle\Security\Core\UserProvider

services:
    talker:
        class: Lider\Bundle\LiderBundle\Lib\Talker
        arguments:
              entityManager: "@doctrine.orm.entity_manager"
              container: "@service_container"

    notificationService:
        class: Lider\Bundle\LiderBundle\Lib\NotificationService
        arguments:
          dm: "@doctrine.odm.mongodb.document_manager"
          co: "@service_container"
          mailer: "@mailer"
          templating: "@templating"

    notificationWorker:
        class: Lider\Bundle\LiderBundle\Worker\NotificationWorker
        arguments:
          co: "@service_container"

    simulatorWorker:
        class: Lider\Bundle\LiderBundle\Worker\SimulatorWorker
        arguments:
          co: "@service_container"

    checkerWorker:
        class: Lider\Bundle\LiderBundle\Worker\CheckerWorker
        arguments:
          co: "@service_container"

    login.security.authentication.provider:
        class: Lider\Bundle\LiderBundle\Security\Authentication\Provider\Provider

    login.security.authentication.listener:
        class: Lider\Bundle\LiderBundle\Security\Firewall\Listener
        parent: security.authentication.listener.abstract
        abstract: true
        #arguments: ["@security.context", "@security.authentication.manager", "@talker"]

    hauth.security.authentication.provider:
        class: Lider\Bundle\LiderBundle\Security\Authentication\Provider\HeaderAuthenticationProvider

    hauth.security.authentication.listener:
        class: Lider\Bundle\LiderBundle\Security\Firewall\HeaderAuthenticationListener
        parent: security.authentication.listener.abstract
        abstract: true
        #arguments: ["@security.context", "@security.authentication.manager", "@talker"]

    lider_user_provider:
        class: "%lider.security.core.provider.class%"
        arguments: ["@service_container"]

    question_manager:
        class: Lider\Bundle\LiderBundle\Lib\QuestionManager
        arguments:            
              co: "@service_container"

    parameters_manager:
        class: Lider\Bundle\LiderBundle\Lib\ParametersManager

    game_manager:
        class: Lider\Bundle\LiderBundle\Lib\GameManager
        arguments:
              em: "@doctrine.orm.entity_manager"
              dm: "@doctrine.odm.mongodb.document_manager"
              pm: "@parameters_manager"
              qm: "@question_manager"
              co: "@service_container"
